# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(597, 276)
        MainWindow.setMinimumSize(QtCore.QSize(597, 276))
        MainWindow.setMaximumSize(QtCore.QSize(597, 276))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setProperty("setFixedSize", "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(597, 256))
        self.centralwidget.setMaximumSize(QtCore.QSize(597, 256))
        self.centralwidget.setObjectName("centralwidget")
        self.background_color_label = QtWidgets.QLabel(self.centralwidget)
        self.background_color_label.setGeometry(QtCore.QRect(10, 0, 611, 281))
        self.background_color_label.setStyleSheet(
            "background-color: rgb(103, 139, 255);")
        self.background_color_label.setText("")
        self.background_color_label.setObjectName("background_color_label")
        self.text_for_directory = QtWidgets.QTextEdit(self.centralwidget)
        self.text_for_directory.setGeometry(QtCore.QRect(20, 20, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.text_for_directory.setFont(font)
        self.text_for_directory.setAcceptDrops(True)
        self.text_for_directory.setAutoFillBackground(False)
        self.text_for_directory.setReadOnly(True)
        self.text_for_directory.setObjectName("text_for_directory")
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setGeometry(QtCore.QRect(440, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.select_button.setFont(font)
        self.select_button.setObjectName("select_button")
        self.label_for_counter = QtWidgets.QLineEdit(self.centralwidget)
        self.label_for_counter.setGeometry(QtCore.QRect(20, 60, 131, 20))
        self.label_for_counter.setReadOnly(True)
        self.label_for_counter.setObjectName("label_for_counter")
        self.convert_button = QtWidgets.QPushButton(self.centralwidget)
        self.convert_button.setGeometry(QtCore.QRect(440, 60, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.convert_button.setFont(font)
        self.convert_button.setObjectName("convert_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 411, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            r"converterSources\srcs\img\nelo-logo.svg"))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Converter .ret para .txt"))
        self.text_for_directory.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                   "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                   "p, li { white-space: pre-wrap; }\n"
                                                   "</style></head><body style=\" font-family:\'Arial\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                   "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">Escolha a </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">PASTA</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\"> dos arquivos a serem convertidos</span></p></body></html>"))
        self.text_for_directory.setPlaceholderText(_translate(
            "MainWindow", "Escolha a PASTA dos arquivos a serem convertidos"))
        self.select_button.setText(_translate(
            "MainWindow", "Selecionar Pasta"))
        self.label_for_counter.setText(_translate(
            "MainWindow", "Arquivos renomeados: "))
        self.convert_button.setText(_translate("MainWindow", "Converter"))
